name: Run tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Lint TypeScript files
        run: npx eslint .
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Compile TypeScript to JavaScript
        run: ./node_modules/.bin/tsc
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Run tests
        run: npm test