name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NPM dependencies
        run: npm install

      - name: Run tests
        run: npm test