name: Run tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NPM install
        run: |
          npm install
          npm test
          node --version
          npm --version